// Every piece of text on the page lives here, so a translation (e.g. 中文)
// only means adding another block like `en`.
const STRINGS = {
  en: {
    appTitle: "CSS Exec Portal",
    appSubtitle: "Chinese Students' Society · University of Calgary",
    demoBanner: "Demo mode: made-up data, not connected to CSS",
    passwordLabel: "Exec password",
    nameLabel: "Who are you?",
    namePlaceholder: "Your name",
    signIn: "Sign in",
    signingIn: "Signing in…",
    doorSignIn: "Door sign-in (name only)",
    doorHint: "Volunteers at the door: type your name above, then press this button. It only works while an exec has entry open. Execs use the password.",
    setDoorPw: "Door password (optional)",
    setDoorNoteSet: "A door password is set. Door volunteers must type it with their name.",
    setDoorNoteNone: "No door password. Door volunteers sign in with just their name, and only while entry is open.",
    setDoorClear: "Remove the door password",
    setDoorClearConfirm: "Remove the door password? Door volunteers will sign in with just their name.",
    signOut: "Sign out",
    signedInAs: "Signed in as",
    roleAdmin: "Admin",
    tabMembers: "Members",
    tabEvents: "Events",
    tabPayments: "Payments",
    tabDoor: "Door",
    tabActivity: "Activity",
    fullPortal: "Full portal",
    scannerTitle: "CSS Door Scanner",
    sendToDesk: "Send to help desk",
    colOrder: "Order",
    colPayer: "Payer",
    colPeople: "People",
    colTotal: "Total",
    tileStillToCome: "Still to come",
    tilePaidCount: (n) => `${n} ticket${n === 1 ? "" : "s"} paid`,
    tileOrdersAwaiting: (n) => `${n} order${n === 1 ? "" : "s"} awaiting`,
    tileOverdue: "Waiting too long",
    tileOverdueNote: (h) => `unpaid over ${h} hours`,
    tileSpots: "Spots taken",
    tileSpotsNote: (n) => `${n} left`,
    tabSettings: "Settings",
    actAll: "Everything",
    actPayments: "Payments",
    actDoor: "Door",
    actEdits: "Edits",
    actEvents: "Events",
    actSettings: "Settings",
    actAllEvents: "All events",
    actEveryone: "Everyone",
    actLoading: "Loading…",
    actNone: "Nothing matches.",
    actCount: (n) => `${n} change${n === 1 ? "" : "s"}, newest first`,
    actTruncated: (n) => `Showing the latest ${n}. Pick a bigger number or narrow it with the filters.`,
    setLoading: "Loading settings…",
    setGeneralTitle: "Payments and contact",
    setEtransfer: "E-transfer email (where people send money)",
    setEtransferHint: "Shown on the payment screen and in emails. Change it only if CSS gets a new e-transfer address.",
    setContact: "Contact email (bottom of the public pages)",
    setInstagram: "Instagram link",
    setSave: "Save",
    setSaved: (what) => `Saved: ${what}.`,
    setNothing: "Nothing to change.",
    setSiteUrl: (url) => `The public site is at ${url}`,
    setNoSiteUrl: "The public site address isn't remembered yet. It is set the first time someone marks an order paid.",
    setMembershipTitle: "Membership sheet",
    setMembershipHint: "Where the system looks up members. Each year there's a new sheet: paste its link here. It is read before saving, so a wrong link can't break anything.",
    setSheet: "Sheet link or ID",
    setTab: "Tab name",
    setTestSave: "Test and save",
    setPasswordsTitle: "Passwords",
    setPwNote: (exec, admin) => `Exec password: ${exec ? "set" : "NOT set"} · Admin password: ${admin ? "set" : "NOT set"}. Passwords are never shown.`,
    setExecPw: "New exec password (type it twice)",
    setAdminPw: "New admin password (type it twice)",
    setPwHint: "At least 8 characters, and the two passwords must differ. Leave a pair blank to keep it as it is. Never write passwords in a document or a chat.",
    setPwSave: "Change password(s)",
    setPwMismatch: "The two boxes don't match.",
    setPwConfirm: "Change the password? Everyone else will be signed out and must use the new one.",
    setEveryoneOut: "Everyone else was signed out.",
    setSessionsTitle: "Sign everyone out",
    setSessionsHint: "Use this if a phone or laptop was left signed in. You stay signed in.",
    setSignOutAll: "Sign everyone else out",
    setSignOutConfirm: "Sign everyone else out now?",
    setHealthTitle: "Health check",
    setHealthRun: "Run health check",
    setChecking: "Checking…",
    setOk: "OK",
    setProblem: "Problem",
    setVersion: (v) => `System version ${v}`,
    setLastError: "Last error",
    setNoError: "No errors recorded.",
    emTitle: "Email wording",
    emHint: "Change the words in the emails people get. The look stays the same. A blank box uses the standard wording.",
    emPick: "Which email",
    emSubject: "Subject line",
    emHeading: "Big heading",
    emSubheading: "Line under the heading",
    emIntro: "Text at the top",
    emClosing: "Text at the bottom",
    emFormatHint: "A blank line starts a new paragraph. **Two stars** around words make them bold. Type just a dash (-) to show nothing in that spot.",
    emFills: (list) => list.length ? `You can use: ${list.map((p) => "{" + p + "}").join(" ")}. They are filled in for each person.` : "No fill-ins for this one.",
    emDefault: "Standard wording:",
    emPreview: "Preview",
    emReset: "Use standard wording",
    emResetConfirm: "Clear this email's wording and use the standard text?",
    emTestTo: "Send a test to",
    emTest: "Send test email",
    emSaved: "Saved.",
    emSent: (to) => `Test sent to ${to}.`,
    emBrandTitle: "Signature and button",
    emSigner: "Name at the bottom of every email",
    emRole: "Role under the name",
    emColor: "Button colour",
    emBrandReset: "Use standard signature",
    emBrandResetConfirm: "Go back to the standard name, role and colour?",
    entryOpen: "🟢 Entry OPEN (tap to close)",
    entryOpenPlain: "Entry open",
    entryClosedPlain: "Entry closed (ask the help desk)",
    entryClosed: "🔴 Entry CLOSED (tap to open)",
    confirmCloseEntry: "Close entry? Scanners will stop checking people in.",
    doorCounts: (inside, paid, awaiting) => `${inside} checked in · ${paid} paid · ${awaiting} not paid`,
    startCamera: "📷 Start scanning",
    stopCamera: "Stop camera",
    cameraError: "Couldn't open the camera. Allow camera access, or type the ticket ID below.",
    readyToScan: "Point the camera at a ticket QR code.",
    checking: "Checking…",
    tapForNext: "Tap for next scan",
    recentTitle: (n) => `Recent check-ins (${n})`,
    undo: "Undo",
    confirmUndo: (name) => `Undo ${name}'s check-in? Their ticket can then be scanned again.`,
    undone: (name) => `${name}'s check-in was undone.`,
    confirmDeskCheckIn: (name, flag) => `${name}: ${flag}\n\nChecked this at the help desk? Let them in?`,
    walkIn: "+ Walk-in",
    walkInTitle: "Walk-in",
    walkInName: "Name",
    walkInUcid: "UCID (optional)",
    walkInMemberId: "Member ID (optional)",
    walkInPaidBy: "Paid by",
    cash: "Cash",
    etransfer: "E-transfer",
    walkInSubmit: "Add & check in",
    cancel: "Cancel",
    ticket: "Ticket",
    find: "Find",
    manualPlaceholder: "Ticket ID or name",
    checkIn: "Check in",
    noMatch: "No one by that name or ID.",
    unpaidTitle: (n) => `Help desk: not paid yet (${n})`,
    flaggedTitle: (n) => `Help desk: please check (${n})`,
    nobody: "Nobody here 🎉",
    insideMark: (time) => `checked in ${time}`,
    markPaidShort: (amount) => `Mark paid ${amount}`,
    payEvent: "Event",
    noEventsForPayments: "No events yet.",
    loadingOrders: "Loading registrations…",
    paySummary: (paid, cap, awaiting) => `${paid}${cap} tickets paid · ${awaiting} orders awaiting payment`,
    loadMore: "Show more",
    attCountOf: (shown, total) => (shown >= total ? `${total} ${total === 1 ? "person" : "people"}` : `Showing ${shown} of ${total} people`),
    orderCountOf: (shown, total) => (shown >= total ? `${total} order${total === 1 ? "" : "s"}` : `Showing ${shown} of ${total} orders`),
    unsentEmails: (n) => `${n} ticket email${n === 1 ? "" : "s"} waiting to be sent (daily email limit).`,
    sendNow: "Send now",
    filterAwaiting: "Awaiting",
    filterPaid: "Paid",
    filterClosed: "Refunded / cancelled",
    filterAll: "All",
    filterOverdue: (n) => `Waiting too long (${n})`,
    overdueNotice: (n, hours) => `${n} order${n === 1 ? "" : "s"} unpaid for over ${hours} hours.`,
    attDownload: "Download list (CSV)",
    attDownloadNone: "Nothing to download yet.",
    mailAll: "Email everyone",
    mailTitle: (event) => `Email people registered for ${event}`,
    mailHint: "Each person gets their own copy, in the usual look. Use Preview to see it first. The same address only gets one email.",
    mailWho: "Who gets it",
    mailWhoAll: "Everyone registered (paid and not paid)",
    mailWhoPaid: "Only people who have paid",
    mailWhoUnpaid: "Only people who haven't paid yet",
    mailMessage: "Message",
    mailFills: "You can use {name} {event} {when} {where}. A blank line starts a new paragraph.",
    mailSend: "Send",
    mailCount: (n, tests, left) => `${n} ${n === 1 ? "person" : "people"} will get this.` + (tests ? ` (${tests} test address${tests === 1 ? "" : "es"} skipped.)` : "") + ` Emails left today: ${left}.`,
    mailConfirm: (n) => `Send this email to ${n} ${n === 1 ? "person" : "people"}? You can't undo it.`,
    mailDone: (sent, failed) => `${sent} email${sent === 1 ? "" : "s"} sent.` + (failed ? ` ${failed} failed.` : ""),
    mailNobody: "Nobody to email with that choice.",
    sendReminders: "Send reminders",
    confirmReminders: (n, tests, left) => `Send a payment reminder email to ${n} ${n === 1 ? "person" : "people"}?` +
      (tests ? `\n\n(${tests} more use test addresses and won't be emailed.)` : "") +
      `\n\nEmails left today: ${left}. Each order is only reminded once every 2 days.`,
    remindersNone: "Nobody needs a reminder right now.",
    remindersSent: (sent, failed) => `${sent} reminder${sent === 1 ? "" : "s"} sent.` + (failed ? ` ${failed} couldn't be sent (daily email limit). Try again tomorrow.` : ""),
    pickOrder: "Select this order",
    bulkHint: "Tick orders to mark several paid at once.",
    bulkSelected: (n, total) => `${n} selected · ${total}`,
    bulkAll: (n) => `Select all shown (${n})`,
    bulkClear: "Clear",
    bulkPay: (n) => `Mark ${n} paid`,
    confirmBulk: (n, total, list) => `Mark ${n} order${n === 1 ? "" : "s"} paid (${total} in all)?\n\n${list}\n\nDid you receive exactly these amounts? Everyone in these orders will be emailed their ticket.`,
    bulkDone: (n, emails) => `${n} order${n === 1 ? "" : "s"} marked paid, ${emails} ticket email${emails === 1 ? "" : "s"} sent.`,
    bulkSkipped: (list) => `Skipped: ${list}`,
    payMoney: (received, expected) => ` · ${received} received of ${expected} expected`,
    addOrder: "+ Add paid registration",
    addTitle: (event) => `Add a paid registration: ${event}`,
    addHint: "For someone who paid (e-transfer or cash) without registering online. They're added as paid and emailed their ticket.",
    addEmailHint: "Needed to send their ticket.",
    addSave: "Add as paid",
    added: (code, sent, flag) => `Added ${code} as paid.` + (sent ? " Ticket emailed." : "") + (flag ? ` Note: ${flag}` : ""),
    paySearchPlaceholder: "Payment code, name, email or e-transfer name",
    noOrders: "Nothing here.",
    orderCount: (n) => `${n} order${n === 1 ? "" : "s"}`,
    etransferNameLabel: "E-transfer name",
    registered: "Registered",
    paidByLabel: (who, when) => `Marked paid by ${who}, ${when}`,
    markPaid: (amount) => `Mark paid (${amount})`,
    confirmPaid: (amount, code, who) => `Did you receive exactly ${amount} for ${code} (${who})?

Everyone in this order will be emailed their ticket.`,
    overCapacity: (msg) => `${msg}

Mark it paid anyway?`,
    markedPaid: (sent, waiting) => `Paid ✓ ${sent} ticket email${sent === 1 ? "" : "s"} sent${waiting ? `, ${waiting} waiting (daily limit)` : ""}.`,
    refund: "Refund / cancel",
    refundPrompt: (code, status) => status === "paid"
      ? `Refund ${code}? Their spot opens up again. Send the money back by e-transfer yourself.

Reason (optional):`
      : `Cancel ${code}? (Not paid yet.)

Reason (optional):`,
    resend: "Resend tickets",
    resent: (sent) => `Sent ${sent} ticket email${sent === 1 ? "" : "s"} again.`,
    statusAwaiting: "Awaiting payment",
    statusPaid: "Paid",
    statusRefunded: "Refunded",
    statusCancelled: "Cancelled",
    checkedInMark: "checked in",
    emailedMark: "ticket emailed",
    openTicket: "Ticket ↗",
    editPerson: "Edit",
    editTitle: "Edit person",
    editName: "Name",
    editEmail: "Email",
    editEmailHint: "Their ticket is sent again if this changes.",
    editAdminTitle: "Admin only",
    editAdminLocked: "More fields (ticket type, UCID, member ID, answers, the order's payer details) need the admin password.",
    editUcid: "UCID",
    editMemberId: "Member ID",
    editMemberHint: "Changing the member ID, UCID or ticket type checks the Membership sheet again.",
    editType: "Ticket type",
    editFlag: "Help-desk flag",
    editFlagHint: "Clear this to remove the warning from the door. Leave as is for the usual check.",
    editAnswers: "Answers",
    editOrderTitle: (code) => `Order ${code}`,
    editPayerName: "Payer name",
    editPayerEmail: "Payer email",
    editEtransferName: "Name on the e-transfer",
    editNotes: "Order notes",
    editSave: "Save changes",
    editSaving: "Saving…",
    editNothing: "Nothing was changed.",
    edited: (sent) => sent ? `Saved. Ticket re-sent to the new email.` : "Saved.",
    editedTotal: (was, now, status) => `Order total is now ${money(now)} (was ${money(was)}).` +
      (status === "paid" ? (now > was ? " Collect the difference." : " Send the difference back by e-transfer.") : " The payer's email still shows the old amount."),
    reconnecting: "Connection is slow. Trying again…",
    liveInside: "inside",
    liveNotPaid: (n) => `${n} not paid yet`,
    duplicate: "Duplicate",
    duplicateTitle: (name) => `New event (copy of ${name})`,
    duplicateHint: "Copied from another event. Pick the new date and check the details before saving.",
    attendees: "Attendees",
    attendeesTitle: "Everyone registered",
    attSearchPlaceholder: "Name, email, UCID, member ID or payment code",
    attSortName: "Sort: name",
    attSortType: "Sort: ticket type",
    attSortNewest: "Sort: newest first",
    attFilterActive: "Active",
    attFilterPaid: "Paid",
    attFilterAwaiting: "Awaiting",
    attFilterInside: "Checked in",
    attFilterNotArrived: "Not arrived",
    attFilterFlagged: "Flagged",
    attFilterClosed: "Refunded / cancelled",
    attFilterAll: "All",
    attCount: (n) => `${n} ${n === 1 ? "person" : "people"}`,
    attNone: "Nobody matches.",
    attLoading: "Loading…",
    tileRegistered: "Registered",
    tilePaid: "Paid",
    tileAwaiting: "Awaiting payment",
    tileInside: "Checked in",
    tileNotArrived: "Paid, not arrived",
    tileSpotsLeft: "Spots left",
    tileReceived: "Money received",
    tileWaiting: "Money still to come",
    tileFlagged: "Flagged for help desk",
    byTypeTitle: "By ticket type",
    byTypeLine: (paid, awaiting, inside) => `${paid} paid · ${awaiting} awaiting · ${inside} checked in`,
    answersTitle: "Answers to your questions",
    answersLine: (paid, awaiting) => awaiting ? `${paid} paid + ${awaiting} awaiting` : `${paid}`,
    noAnswers: "No answers yet.",
    refreshed: "Refresh",
    eventsTitle: "Events",
    newEvent: "+ New event",
    loadingEvents: "Loading events…",
    noEvents: "No events yet. Create the first one.",
    statusDraft: "Draft",
    statusPublished: "Published",
    statusClosed: "Closed",
    edit: "Edit",
    publish: "Publish",
    unpublish: "Back to draft",
    closeRegistration: "Close registration",
    reopen: "Reopen",
    viewPublicPage: "Public page ↗",
    backToEvents: "Back to events",
    newEventTitle: "New event",
    editEventTitle: "Edit event",
    evName: "Event name",
    evImage: "Event image",
    evDate: "Date",
    evStart: "Starts",
    evEnd: "Ends",
    evLocation: "Location",
    evDescription: "Description",
    evCapacity: "Capacity (blank = no limit)",
    evCapacityRule: "What counts toward capacity",
    evCapacityPaid: "Paid tickets only",
    evCapacityAll: "Every sign-up",
    evTickets: "Ticket types & prices",
    ticketName: "Ticket name",
    ticketPrice: "Price $",
    needsMembership: "Members only (checks member ID / UCID)",
    addTicketType: "+ Add ticket type",
    evQuestions: "Extra questions",
    evQuestionsHint: "Name, email and UCID are always asked. Add anything else here.",
    questionLabel: "Question",
    questionType: "Answer type",
    typeText: "Short answer",
    typeChoice: "Choose one",
    questionOptions: "Options, separated by commas",
    required: "Required",
    addQuestion: "+ Add question",
    remove: "Remove",
    evCloses: "Registration closes",
    evClosesHint: "Leave blank to close automatically when the event starts.",
    archive: "Archive",
    restore: "Restore",
    confirmArchive: (name) => `Archive "${name}"?

Its tickets and orders move out of the everyday sheet into this school year's archive spreadsheet, so the system stays fast. It disappears from the public site and the Payments and Door tabs. You can still open its attendees list and download it. Nothing is deleted, and Restore brings it all back.

This can take up to a minute for a big event.`,
    confirmRestore: (name) => `Restore "${name}"? Its tickets and orders move back into the everyday sheet and it shows as Closed.`,
    deleteEvent: "Delete",
    deletePrompt: (name) => `DELETE "${name}" FOR GOOD?

This removes the event and every ticket and order on it. It cannot be undone. (To keep the history, use Archive instead.)

Type the event's exact name to confirm:`,
    deleteMoneyConfirm: "Delete it anyway? The record of that money will be gone (old backups in Drive still have a copy).",
    deletedDone: (name, tickets, orders) => `Deleted "${name}" (${tickets} tickets, ${orders} orders).`,
    archiving: "Archiving…",
    restoring: "Restoring…",
    archivedBanner: (year) => `Archived (${year}). Read only: nothing here can be changed. Press Restore on the Events list to change it.`,
    archivedDone: (tickets, orders) => `Archived: ${tickets} tickets and ${orders} orders moved to the archive.`,
    restoredDone: (tickets, orders) => `Restored: ${tickets} tickets and ${orders} orders are back.`,
    showArchived: (n) => `Show archived events (${n})`,
    hideArchived: "Hide archived events",
    statusArchived: "Archived",
    evCodePrefix: "Payment code letters",
    evCodePrefixHint: "Starts every payment code for this event, e.g. MGN-4821. Leave blank to use the event's initials.",
    saveDraft: "Save draft",
    savePublish: "Save & publish",
    saving: "Saving…",
    saved: "Saved.",
    uploading: "Uploading image…",
    uploaded: "Image uploaded.",
    imageTooBig: "Pick an image under 15 MB.",
    confirmPublish: "Publish this event? Anyone with the link will be able to see it.",
    free: "Free",
    countsLine: (paid, cap, awaiting) => `${paid}${cap} paid · ${awaiting} awaiting payment`,
    searchLabel: "Search members",
    searchPlaceholder: "Name, UCID, member ID or email",
    searchHint: "Type at least 2 characters.",
    searching: "Searching…",
    noResults: "No member matches",
    resultsCount: (n) => n === 1 ? "1 member" : `${n} members`,
    showingFirst: (shown, total) => `Showing ${shown} of ${total} members. Type more to narrow it down.`,
    paid: "Paid",
    unpaid: "Not paid",
    cardSent: "Card sent",
    cardNotSent: "Card not sent",
    noId: "No ID yet",
    back: "Back to results",
    fieldMemberId: "Member ID",
    fieldUcid: "UCID",
    fieldEmail: "Email",
    fieldPaid: "Payment",
    fieldCard: "Membership card",
    fieldSignedUp: "Signed up",
    fieldPayMethod: "Payment method",
    fieldPayWhen: "Paid when",
    fieldPayWhere: "Paid where",
    fieldPayWho: "Received by",
    readOnlyNote: "View only: changes still happen in the current system for now.",
    errors: {
      WRONG_PASSWORD: "That password isn't right.",
      TOO_MANY_TRIES: "Too many wrong tries. Wait 10 minutes and try again.",
      NAME_NEEDED: "Pick your name first.",
      NOT_LOGGED_IN: "You were signed out. Please sign in again.",
      SETUP_NEEDED: "The system isn't set up yet. Ask the tech lead.",
      NETWORK: "Can't reach the CSS system. Check your internet and try again.",
      TEMPORARY: "Google was slow for a moment. Try again.",
      BUSY: "The system is busy. Try again in a moment.",
      ADMIN_ONLY: "Only the admin password can do that.",
      DOOR_CLOSED: "Door scanning is closed right now. An exec has to open entry first.",
      DOOR_PASSWORD_NEEDED: "Ask an exec for the door password, type it in the password box, then press the door button again.",
      DOOR_ONLY: "Door sign-in can only scan tickets. Sign out and use the exec password for this.",
      DEFAULT: "Something went wrong. Try again."
    }
  }
};

const T = STRINGS.en;
