// Every piece of text on the page lives here, so a translation (e.g. 中文)
// only means adding another block like `en`.
const STRINGS = {
  en: {
    appTitle: "CSS Exec Portal",
    appSubtitle: "Chinese Students' Society · University of Calgary",
    demoBanner: "Demo mode: made-up data, not connected to CSS",
    passwordLabel: "Exec password",
    nameLabel: "Who are you?",
    namePlaceholder: "Your name",
    signIn: "Sign in",
    signingIn: "Signing in…",
    signOut: "Sign out",
    signedInAs: "Signed in as",
    roleAdmin: "Admin",
    tabMembers: "Members",
    tabEvents: "Events",
    tabPayments: "Payments",
    tabDoor: "Door",
    entryOpen: "🟢 Entry OPEN (tap to close)",
    entryClosed: "🔴 Entry CLOSED (tap to open)",
    confirmCloseEntry: "Close entry? Scanners will stop checking people in.",
    doorCounts: (inside, paid, awaiting) => `${inside} checked in · ${paid} paid · ${awaiting} not paid`,
    startCamera: "📷 Start scanning",
    stopCamera: "Stop camera",
    cameraError: "Couldn't open the camera. Allow camera access, or type the ticket ID below.",
    readyToScan: "Point the camera at a ticket QR code.",
    checking: "Checking…",
    tapForNext: "Tap for next scan",
    recentTitle: (n) => `Recent check-ins (${n})`,
    undo: "Undo",
    confirmUndo: (name) => `Undo ${name}'s check-in? Their ticket can then be scanned again.`,
    undone: (name) => `${name}'s check-in was undone.`,
    confirmDeskCheckIn: (name, flag) => `${name}: ${flag}\n\nChecked this at the help desk? Let them in?`,
    walkIn: "+ Walk-in",
    walkInTitle: "Walk-in",
    walkInName: "Name",
    walkInUcid: "UCID (optional)",
    walkInMemberId: "Member ID (optional)",
    walkInPaidBy: "Paid by",
    cash: "Cash",
    etransfer: "E-transfer",
    walkInSubmit: "Add & check in",
    cancel: "Cancel",
    ticket: "Ticket",
    find: "Find",
    manualPlaceholder: "Ticket ID or name",
    checkIn: "Check in",
    noMatch: "No one by that name or ID.",
    unpaidTitle: (n) => `Help desk: not paid yet (${n})`,
    flaggedTitle: (n) => `Help desk: please check (${n})`,
    nobody: "Nobody here 🎉",
    insideMark: (time) => `checked in ${time}`,
    markPaidShort: (amount) => `Mark paid ${amount}`,
    payEvent: "Event",
    noEventsForPayments: "No events yet.",
    loadingOrders: "Loading registrations…",
    paySummary: (paid, cap, awaiting) => `${paid}${cap} tickets paid · ${awaiting} orders awaiting payment`,
    unsentEmails: (n) => `${n} ticket email${n === 1 ? "" : "s"} waiting to be sent (daily email limit).`,
    sendNow: "Send now",
    filterAwaiting: "Awaiting",
    filterPaid: "Paid",
    filterClosed: "Refunded / cancelled",
    filterAll: "All",
    filterOverdue: (n) => `Waiting too long (${n})`,
    overdueNotice: (n, hours) => `${n} order${n === 1 ? "" : "s"} unpaid for over ${hours} hours.`,
    sendReminders: "Send reminders",
    confirmReminders: (n, tests, left) => `Send a payment reminder email to ${n} ${n === 1 ? "person" : "people"}?` +
      (tests ? `\n\n(${tests} more use test addresses and won't be emailed.)` : "") +
      `\n\nEmails left today: ${left}. Each order is only reminded once every 2 days.`,
    remindersNone: "Nobody needs a reminder right now.",
    remindersSent: (sent, failed) => `${sent} reminder${sent === 1 ? "" : "s"} sent.` + (failed ? ` ${failed} couldn't be sent (daily email limit). Try again tomorrow.` : ""),
    pickOrder: "Select this order",
    bulkHint: "Tick orders to mark several paid at once.",
    bulkSelected: (n, total) => `${n} selected · ${total}`,
    bulkAll: (n) => `Select all shown (${n})`,
    bulkClear: "Clear",
    bulkPay: (n) => `Mark ${n} paid`,
    confirmBulk: (n, total, list) => `Mark ${n} order${n === 1 ? "" : "s"} paid (${total} in all)?\n\n${list}\n\nDid you receive exactly these amounts? Everyone in these orders will be emailed their ticket.`,
    bulkDone: (n, emails) => `${n} order${n === 1 ? "" : "s"} marked paid, ${emails} ticket email${emails === 1 ? "" : "s"} sent.`,
    bulkSkipped: (list) => `Skipped: ${list}`,
    payMoney: (received, expected) => ` · ${received} received of ${expected} expected`,
    addOrder: "+ Add paid registration",
    addTitle: (event) => `Add a paid registration: ${event}`,
    addHint: "For someone who paid (e-transfer or cash) without registering online. They're added as paid and emailed their ticket.",
    addEmailHint: "Needed to send their ticket.",
    addSave: "Add as paid",
    added: (code, sent, flag) => `Added ${code} as paid.` + (sent ? " Ticket emailed." : "") + (flag ? ` Note: ${flag}` : ""),
    paySearchPlaceholder: "Payment code, name, email or e-transfer name",
    noOrders: "Nothing here.",
    orderCount: (n) => `${n} order${n === 1 ? "" : "s"}`,
    etransferNameLabel: "E-transfer name",
    registered: "Registered",
    paidByLabel: (who, when) => `Marked paid by ${who}, ${when}`,
    markPaid: (amount) => `Mark paid (${amount})`,
    confirmPaid: (amount, code, who) => `Did you receive exactly ${amount} for ${code} (${who})?

Everyone in this order will be emailed their ticket.`,
    overCapacity: (msg) => `${msg}

Mark it paid anyway?`,
    markedPaid: (sent, waiting) => `Paid ✓ ${sent} ticket email${sent === 1 ? "" : "s"} sent${waiting ? `, ${waiting} waiting (daily limit)` : ""}.`,
    refund: "Refund / cancel",
    refundPrompt: (code, status) => status === "paid"
      ? `Refund ${code}? Their spot opens up again. Send the money back by e-transfer yourself.

Reason (optional):`
      : `Cancel ${code}? (Not paid yet.)

Reason (optional):`,
    resend: "Resend tickets",
    resent: (sent) => `Sent ${sent} ticket email${sent === 1 ? "" : "s"} again.`,
    statusAwaiting: "Awaiting payment",
    statusPaid: "Paid",
    statusRefunded: "Refunded",
    statusCancelled: "Cancelled",
    checkedInMark: "checked in",
    emailedMark: "ticket emailed",
    openTicket: "Ticket ↗",
    editPerson: "Edit",
    editTitle: "Edit person",
    editName: "Name",
    editEmail: "Email",
    editEmailHint: "Their ticket is sent again if this changes.",
    editAdminTitle: "Admin only",
    editAdminLocked: "More fields (ticket type, UCID, member ID, answers, the order's payer details) need the admin password.",
    editUcid: "UCID",
    editMemberId: "Member ID",
    editMemberHint: "Changing the member ID, UCID or ticket type checks the Membership sheet again.",
    editType: "Ticket type",
    editFlag: "Help-desk flag",
    editFlagHint: "Clear this to remove the warning from the door. Leave as is for the usual check.",
    editAnswers: "Answers",
    editOrderTitle: (code) => `Order ${code}`,
    editPayerName: "Payer name",
    editPayerEmail: "Payer email",
    editEtransferName: "Name on the e-transfer",
    editNotes: "Order notes",
    editSave: "Save changes",
    editSaving: "Saving…",
    editNothing: "Nothing was changed.",
    edited: (sent) => sent ? `Saved. Ticket re-sent to the new email.` : "Saved.",
    editedTotal: (was, now, status) => `Order total is now ${money(now)} (was ${money(was)}).` +
      (status === "paid" ? (now > was ? " Collect the difference." : " Send the difference back by e-transfer.") : " The payer's email still shows the old amount."),
    reconnecting: "Connection is slow. Trying again…",
    liveInside: "inside",
    liveNotPaid: (n) => `${n} not paid yet`,
    duplicate: "Duplicate",
    duplicateTitle: (name) => `New event (copy of ${name})`,
    duplicateHint: "Copied from another event. Pick the new date and check the details before saving.",
    attendees: "Attendees",
    attendeesTitle: "Everyone registered",
    attSearchPlaceholder: "Name, email, UCID, member ID or payment code",
    attSortName: "Sort: name",
    attSortType: "Sort: ticket type",
    attSortNewest: "Sort: newest first",
    attFilterActive: "Active",
    attFilterPaid: "Paid",
    attFilterAwaiting: "Awaiting",
    attFilterInside: "Checked in",
    attFilterNotArrived: "Not arrived",
    attFilterFlagged: "Flagged",
    attFilterClosed: "Refunded / cancelled",
    attFilterAll: "All",
    attCount: (n) => `${n} ${n === 1 ? "person" : "people"}`,
    attNone: "Nobody matches.",
    attLoading: "Loading…",
    tileRegistered: "Registered",
    tilePaid: "Paid",
    tileAwaiting: "Awaiting payment",
    tileInside: "Checked in",
    tileNotArrived: "Paid, not arrived",
    tileSpotsLeft: "Spots left",
    tileReceived: "Money received",
    tileWaiting: "Money still to come",
    tileFlagged: "Flagged for help desk",
    byTypeTitle: "By ticket type",
    byTypeLine: (paid, awaiting, inside) => `${paid} paid · ${awaiting} awaiting · ${inside} checked in`,
    answersTitle: "Answers to your questions",
    answersLine: (paid, awaiting) => awaiting ? `${paid} paid + ${awaiting} awaiting` : `${paid}`,
    noAnswers: "No answers yet.",
    refreshed: "Refresh",
    eventsTitle: "Events",
    newEvent: "+ New event",
    loadingEvents: "Loading events…",
    noEvents: "No events yet. Create the first one.",
    statusDraft: "Draft",
    statusPublished: "Published",
    statusClosed: "Closed",
    edit: "Edit",
    publish: "Publish",
    unpublish: "Back to draft",
    closeRegistration: "Close registration",
    reopen: "Reopen",
    viewPublicPage: "Public page ↗",
    backToEvents: "Back to events",
    newEventTitle: "New event",
    editEventTitle: "Edit event",
    evName: "Event name",
    evImage: "Event image",
    evDate: "Date",
    evStart: "Starts",
    evEnd: "Ends",
    evLocation: "Location",
    evDescription: "Description",
    evCapacity: "Capacity (blank = no limit)",
    evCapacityRule: "What counts toward capacity",
    evCapacityPaid: "Paid tickets only",
    evCapacityAll: "Every sign-up",
    evTickets: "Ticket types & prices",
    ticketName: "Ticket name",
    ticketPrice: "Price $",
    needsMembership: "Members only (checks member ID / UCID)",
    addTicketType: "+ Add ticket type",
    evQuestions: "Extra questions",
    evQuestionsHint: "Name, email and UCID are always asked. Add anything else here.",
    questionLabel: "Question",
    questionType: "Answer type",
    typeText: "Short answer",
    typeChoice: "Choose one",
    questionOptions: "Options, separated by commas",
    required: "Required",
    addQuestion: "+ Add question",
    remove: "Remove",
    evCloses: "Registration closes",
    evClosesHint: "Leave blank to close automatically when the event starts.",
    archive: "Archive",
    restore: "Restore",
    confirmArchive: (name) => `Archive "${name}"? It disappears from the portal and the public site. Nothing is deleted, and it can be restored.`,
    showArchived: (n) => `Show archived events (${n})`,
    hideArchived: "Hide archived events",
    statusArchived: "Archived",
    evCodePrefix: "Payment code letters",
    evCodePrefixHint: "Starts every payment code for this event, e.g. MGN-4821. Leave blank to use the event's initials.",
    saveDraft: "Save draft",
    savePublish: "Save & publish",
    saving: "Saving…",
    saved: "Saved.",
    uploading: "Uploading image…",
    uploaded: "Image uploaded.",
    imageTooBig: "Pick an image under 15 MB.",
    confirmPublish: "Publish this event? Anyone with the link will be able to see it.",
    free: "Free",
    countsLine: (paid, cap, awaiting) => `${paid}${cap} paid · ${awaiting} awaiting payment`,
    searchLabel: "Search members",
    searchPlaceholder: "Name, UCID, member ID or email",
    searchHint: "Type at least 2 characters.",
    searching: "Searching…",
    noResults: "No member matches",
    resultsCount: (n) => n === 1 ? "1 member" : `${n} members`,
    showingFirst: (shown, total) => `Showing ${shown} of ${total} members. Type more to narrow it down.`,
    paid: "Paid",
    unpaid: "Not paid",
    cardSent: "Card sent",
    cardNotSent: "Card not sent",
    noId: "No ID yet",
    back: "Back to results",
    fieldMemberId: "Member ID",
    fieldUcid: "UCID",
    fieldEmail: "Email",
    fieldPaid: "Payment",
    fieldCard: "Membership card",
    fieldSignedUp: "Signed up",
    fieldPayMethod: "Payment method",
    fieldPayWhen: "Paid when",
    fieldPayWhere: "Paid where",
    fieldPayWho: "Received by",
    readOnlyNote: "View only: changes still happen in the current system for now.",
    errors: {
      WRONG_PASSWORD: "That password isn't right.",
      TOO_MANY_TRIES: "Too many wrong tries. Wait 10 minutes and try again.",
      NAME_NEEDED: "Pick your name first.",
      NOT_LOGGED_IN: "You were signed out. Please sign in again.",
      SETUP_NEEDED: "The system isn't set up yet. Ask the tech lead.",
      NETWORK: "Can't reach the CSS system. Check your internet and try again.",
      TEMPORARY: "Google was slow for a moment. Try again.",
      BUSY: "The system is busy. Try again in a moment.",
      ADMIN_ONLY: "Only the admin password can do that.",
      DEFAULT: "Something went wrong. Try again."
    }
  }
};

const T = STRINGS.en;
